version: "3.7"

services:
  odessajavaclub:
    image: jekyll/jekyll:${JEKYLL_VERSION:-3.8.5}
    command: ["jekyll", "serve"]
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
