version: "3.7"

services:
  odessajavaclub:
    image: jekyll/jekyll:${JEKYLL_VERSION:-3.8.5}
    command: ["bundle", "update"]
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
